# Generated by Django 3.0.8 on 2020-08-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
