# Generated by Django 3.0.8 on 2020-08-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colum1', models.CharField(max_length=50)),
                ('colum2', models.CharField(max_length=50)),
                ('colum3', models.CharField(max_length=50)),
            ],
        ),
    ]
