# Generated by Django 3.0.8 on 2020-08-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0002_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
