# Generated by Django 3.0.8 on 2020-08-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0003_auto_20200804_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
